services:
  app:
    environment:
      - NODE_ENV=test
      - PORT=3001
    ports:
      - "3001:3001"
    command: ["npm", "test"]

  # Test database (isolated)
  postgres_test:
    image: postgres:15-alpine
    container_name: postgres_test
    environment:
      POSTGRES_DB: myapp_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    networks:
      - app-network
