services:
  # Main Application - Base Configuration
  app:
    build: .
    container_name: node_app
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
