services:
  app:
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - DEBUG=app:*
    command: ["npm", "run", "dev"]

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: redis_dev
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Development database (optional)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres_dev
  #   environment:
  #     POSTGRES_DB: myapp_dev
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: devpass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

volumes:
  postgres_dev_data:
