# Default Docker Compose - Development Setup
# For production, use: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d
# For testing, use: docker compose -f docker-compose.base.yml -f docker-compose.test.yml up -d

services:
  # Main Application - Development Mode
  app:
    build: .
    container_name: node_app_default
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
