services:
  app:
    build:
      target: development  # Use development stage
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=development
      - DEBUG=app:*  # Enable debug for development
    # Run as current user to avoid permission issues in development
    user: "${UID:-1000}:${GID:-1000}"
    # Add init to handle signals properly
    init: true
    # Other environment variables come from .env via env_file in base.yml
    # Development-specific volume mounts for hot reload
    volumes:
      - .:/app
      - /app/node_modules

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: redis_dev
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Development database (optional)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres_dev
  #   environment:
  #     POSTGRES_DB: myapp_dev
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: devpass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

volumes:
  postgres_dev_data:
