services:
  app:
    build:
      target: production  # Use production stage
    ports:
      - "3000:3000"  # Fixed port for production (behind nginx)
    environment:
      - NODE_ENV=production  # Override for production
      # DEBUG not set = disabled by default
    # No volume mounting in production - use built image
    volumes: []
    # Use built-in container user in production (no volume mounts = no permission issues)
    # d_sirwan: 1001:1001, milad: 1002:1001
    user: "${CONTAINER_USER_ID:-1001}:${CONTAINER_GROUP_ID:-1001}"
    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Production Redis with persistent storage
  redis:
    image: redis:7-alpine
    container_name: redis_prod
    restart: always
    volumes:
      - redis_prod_data:/data
    # No port exposure in production (internal only)
    networks:
      - app-network

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: always
    networks:
      - app-network

volumes:
  redis_prod_data:
