services:
  app:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: ["npm", "start"]
    # No volume mounting in production
    volumes: []

  # Production Redis with persistent storage
  redis:
    image: redis:7-alpine
    container_name: redis_prod
    restart: always
    volumes:
      - redis_prod_data:/data
    # No port exposure in production (internal only)
    networks:
      - app-network

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: always
    networks:
      - app-network

volumes:
  redis_prod_data:
